#!/bin/bash
#

#if not exist ~/.ssh/id_ed25519.pub  ssh-keygen -t ed25519

#yc compute instance list

#
# Запускать первым (до WEB и MONITORING)  - (LOGS/ELK -> WEB -> MONITORING)
#

LOGS_VM1_NAME=vm-elastic
LOGS_VM2_NAME=vm-kibana

ZONE=ru-central1-a
INT_IP_ELASTIC=10.128.0.31 #Elasticsearch
INT_IP_KIBANA=10.128.0.32 #Kibana

MEMORY_SIZE=4GB
DISK_SIZE=10 #GB

echo [logs] > ~/Thesis-on-the-Profession/ansible/hosts

VM_INT_IP=$INT_IP_ELASTIC
for VM_NAME in $LOGS_VM1_NAME $LOGS_VM2_NAME
do
    yc compute instance get $VM_NAME &>/dev/null
    if [ $? -ne 0 ]; then
        echo "ВМ $VM_NAME не найдена. Создаём"
        #yc compute instance create   --name $VM_NAME   --zone $ZONE   --network-interface subnet-name=default-$ZONE,nat-ip-version=ipv4  --memory 2GB  --cores 2  --core-fraction 20  --hostname centos-$VM_NAME  --preemptible   --create-boot-disk image-folder-id=standard-images,size=10,type=network-hdd,image-family=centos-7   --ssh-key ~/.ssh/id_ed25519.pub   --async >/dev/null
        yc compute instance create   --name $VM_NAME   --zone $ZONE   --network-interface subnet-name=default-$ZONE,nat-ip-version=ipv4,address=$VM_INT_IP  --memory $MEMORY_SIZE  --cores 2  --core-fraction 20  --hostname debian-$VM_NAME  --preemptible   --create-boot-disk image-folder-id=standard-images,size=$DISK_SIZE,type=network-hdd,image-family=debian-11   --ssh-key ~/.ssh/id_ed25519.pub   --async >/dev/null
        if [ $? -ne 0 ]; then echo "ОШИБКА. ВМ $VM_NAME не создана"; exit 1; fi 
    else
        echo "ВМ $VM_NAME уже существует"
    fi
    VM_INT_IP=$INT_IP_KIBANA
done

#Ожидаем публикации IP создаваемых ВМ
echo "Ожидаем публикации IP создаваемых ВМ.."
for VM_NAME in $LOGS_VM1_NAME $LOGS_VM2_NAME
do
    VM_IP=""
    until [ -n "$VM_IP" ]
    do
        VM_IP=$(yc compute instance get $VM_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs)
        if [ -n "$VM_IP" ]; then
            echo "$VM_NAME ansible_host=$VM_IP ansible_connection=ssh ansible_ssh_user=yc-user" >> ~/Thesis-on-the-Profession/ansible/hosts
            if [ "$VM_NAME" = "$LOGS_VM1_NAME" ]; then IP_ELASTIC=$VM_IP; fi
            if [ "$VM_NAME" = "$LOGS_VM2_NAME" ]; then IP_KIBANA=$VM_IP; fi
        fi
        sleep 2
    done
done

yc compute instance list


#scp ~/packages/elasticsearch-7.17.11-amd64.deb yc-user@$IP_ELASTIC:/tmp/
#scp ~/packages/kibana-7.17.11-amd64.deb yc-user@$IP_KIBANA:/tmp/

echo "server.port: 5601
server.host: \"0.0.0.0\"" > ~/Thesis-on-the-Profession/logs/kibana.yml
echo "elasticsearch.hosts: [\"http://$INT_IP_ELASTIC:9200\"]" >> ~/Thesis-on-the-Profession/logs/kibana.yml
echo "server.publicBaseUrl: \"http://$IP_KIBANA:5601/\"
elasticsearch.username: \"kibana_system\"
elasticsearch.password: \"elastic\"" >> ~/Thesis-on-the-Profession/logs/kibana.yml


echo "filebeat.inputs:
#- type: filestream
#  id: my-filestream-id
#  enabled: false
#  paths:
#    - /var/log/*.log
- type: filestream
  id: nginx-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/*.log

# ============================== Filebeat modules ==============================
filebeat.config.modules:
  path: \${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================
setup.template.settings:
  index.number_of_shards: 1

# ================================= Dashboards =================================
setup.dashboards.enabled: true

# =================================== Kibana ===================================
setup.kibana:" > ~/Thesis-on-the-Profession/logs/filebeat.yml

echo "  host: \"http://$INT_IP_KIBANA:5601\"
" >> ~/Thesis-on-the-Profession/logs/filebeat.yml

echo "# ================================== Outputs ===================================

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:" >> ~/Thesis-on-the-Profession/logs/filebeat.yml

echo "  hosts: [\"$INT_IP_ELASTIC:9200\"]" >> ~/Thesis-on-the-Profession/logs/filebeat.yml

echo "  username: \"elastic\"
  password: \"elastic\"

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# ============================= X-Pack Monitoring ==============================
monitoring.enabled: true
" >> ~/Thesis-on-the-Profession/logs/filebeat.yml


#sleep 1s

cd ~/Thesis-on-the-Profession/ansible
ansible-playbook logs.yaml





