#!/bin/bash
#

#Проверяем наличие облака
yc resource-manager cloud list &>/dev/null
if [ $? -ne 0 ]; then
    echo "Облако не найдено или нет интерйфейса командной строки Yandex Cloud"
else
    echo "Облако найдено"
fi

#Проверяем / создаем каталог проекта и автоматически VPC
FOLDER_NAME=thesis-on-the-profession
#yc resource-manager folder list |grep "$FOLDER_NAME"
yc resource-manager folder get --name $FOLDER_NAME &>/dev/null
if [ $? -ne 0 ]; then
    echo "Каталог проекта не найден. Создаем в текущем облаке"
    yc resource-manager folder create --name $FOLDER_NAME --description "Проект дипломной работы" &>/dev/null
    if [ $? -ne 0 ]; then
        echo "Каталог проекта не создан"
    else
        echo "Каталог проекта создан"
    fi
else
    echo "Каталог проекта найден"
fi


#Проверяем / создаем сеть и три подсети (VPC)
NETWORK_NAME=poject-network
SUBNET_NAME=
yc vpc network list &>~/$0-yc-network.txt
if [ $? -ne 0 ]; then
    echo "Сети нет. Создаем в каталоге $FOLDER_NAME"
    yc vpc network create --folder-name $FOLDER_NAME --name $NETWORK_NAME --description "Сеть дипломной работы"
else
    echo "Сеть существует"
    #NETWORK_NAME=$(cat ~/$0-yc-network.txt |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs)
    #echo "$NETWORK_NAME"
fi

