#!/bin/bash
#

WEB_VM1_NAME=vm-web1
WEB_VM2_NAME=vm-web2


MONS_VM2_NAME=vm-grafana
INT_IP_GRAFANA=10.128.0.22 # Grafana + Bastion

#IP_INT_WEB1=10.128.0.11
#IP_INT_WEB2=10.129.0.11

#
#Группа безопасности (security-group) для WEB
#
echo -e "# Группа безопасности (security-group) для WEB #\n"
yc vpc security-group get sg-web &>/dev/null
if [ $? -ne 0 ]; then
    echo "## Группа безопасности для WEB не найдена. Создаём..."
    yc vpc security-group create --name sg-web --description "SG для WEB" --rule description="in web server",direction=ingress,port=80,protocol=tcp,v4-cidrs=[0.0.0.0/0] --network-id enp7h0pg1boe7aqbor9g --rule description="from internal Prometheus to Node Exporter",direction=ingress,port=9100,protocol=tcp,v4-cidrs=[10.128.0.0/24] --rule description="from internal Prometheus to Nginx Log Exporter",direction=ingress,port=4040,protocol=tcp,v4-cidrs=[10.128.0.0/24] --rule description="loadbalancer healthchecks",direction=ingress,port=any,protocol=any,predefined=loadbalancer_healthchecks --rule description="to internal Elasticsearch from Filebeat",direction=egress,port=9200,protocol=tcp,v4-cidrs=[10.128.0.0/24] --rule description="from internal Grafana to SSH",direction=ingress,port=22,protocol=tcp,v4-cidrs=[10.128.0.22/24]
    if [ $? -ne 0 ]; then echo "## ОШИБКА. Группа безопасности для WEB не создана."; exit 1; fi 
else
    echo "## Группа безопасности для WEB уже существует."
    yc vpc security-group get sg-web
fi

#
#Подключаем группу безопасности для WEB к сетевому интерфейсу ВМ целевой группы
#
echo -e "# Подключаем группа безопасности (security-group) для WEB #\n # к сетевому интерфейсу ВМ целевой группы #\n"
SG_WEB_ID=$(yc vpc security-group get --name sg-web |grep -e "^id: " |awk '{print $ 2}')
for VM_NAME in $WEB_VM1_NAME $WEB_VM2_NAME
do
    #yc compute instance update-network-interface --name $VM_NAME --network-interface-index 0 --security-group-name sg-web
    yc compute instance update-network-interface --name $VM_NAME --network-interface-index 0 --security-group-id $SG_WEB_ID >/dev/null
    if [ $? -ne 0 ]; then echo "## ОШИБКА. Группа безопасности сетевому интерфейсу ВМ $VM_NAME не назначена."; exit 1; fi
done

#
#Группа безопасности (security-group) для Prometheus
#


#
#Группа безопасности (security-group) для Grafana (Bastion)
#


#
#Группа безопасности (security-group) для Elasticsearch
#


#
#Группа безопасности (security-group) для Kibana
#
