#!/bin/bash
#

#ssh-keygen -t ed25519

#yc compute instance list

VM_NAME=vm-prometheus

ZONE=ru-central1-a


yc compute instance get $VM_NAME &>/dev/null
if [ $? -ne 0 ]; then
    echo "ВМ $VM_NAME не найдена. Создаём"
    yc compute instance create   --name $VM_NAME   --zone $ZONE   --network-interface subnet-name=default-$ZONE,nat-ip-version=ipv4  --memory 4GB  --cores 2  --core-fraction 20  --hostname debian-$VM_NAME  --preemptible   --create-boot-disk image-folder-id=standard-images,size=20,type=network-hdd,image-family=debian-11   --ssh-key ~/.ssh/id_ed25519.pub >/dev/null
    if [ $? -ne 0 ]; then
        echo "ОШИБКА. ВМ $VM_NAME не создана"
    else
        VM_IP=$(yc compute instance get $VM_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs)
        echo [monitor] > ~/Thesis-on-the-Profession/ansible/hosts
        #echo " " >> ~/Thesis-on-the-Profession/ansible/hosts
        echo "$VM_NAME ansible_host=$VM_IP ansible_connection=ssh ansible_ssh_user=yc-user" >> ~/Thesis-on-the-Profession/ansible/hosts
        sleep 25s
    fi 
else
    echo "ВМ $VM_NAME уже существует"
fi

sleep 5s

VM_IP=$(yc compute instance get $VM_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs)

#cd ~/Thesis-on-the-Profession/ansible
#ansible-playbook prometheus.yml

sleep 5s


scp ~/Thesis-on-the-Profession/monitoring/prometheus.service yc-user@$VM_IP:/tmp/
#scp ~/Thesis-on-the-Profession/monitoring/prometheus-install yc-user@$VM_IP:/tmp/
scp ~/Thesis-on-the-Profession/monitoring/prometheus-install-sudo yc-user@$VM_IP:/tmp/
###chmod ugo+x /tmp/prometh*

scp ~/Thesis-on-the-Profession/monitoring/node-exporter.service yc-user@$VM_IP:/tmp/
#scp ~/Thesis-on-the-Profession/monitoring/node-exporter-install yc-user@$VM_IP:/tmp/
scp ~/Thesis-on-the-Profession/monitoring/node-exporter-install-sudo yc-user@$VM_IP:/tmp/
##chmod ugo+x /tmp/node-expor*

scp ~/Thesis-on-the-Profession/monitoring/prometheus.yml yc-user@$VM_IP:/tmp/

#/tmp/prometheus-install-sudo #Без привилегей!
#/tmp/node-exporter-install #Без привилегей!

#sleep 1s

#ansible -b web -m shell -a 'mv -f /tmp/index.nginx-debian.html /var/www/html/'
#ansible -b web -m shell -a 'mv -f /tmp/default /etc/nginx/sites-enabled/'
#ansible -b web -m shell -a 'systemctl restart nginx'

