#!/bin/bash
#

#ssh-keygen -t ed25519

#yc compute instance list

LOGS_VM1_NAME=vm-elastik
LOGS_VM2_NAME=vm-kibana

ZONE=ru-central1-a

echo [logs] > ~/Thesis-on-the-Profession/ansible/hosts

for VM_NAME in $LOGS_VM1_NAME $LOGS_VM2_NAME
do
    yc compute instance get $VM_NAME &>/dev/null
    if [ $? -ne 0 ]; then
        echo "ВМ $VM_NAME не найдена. Создаём"
        #yc compute instance create   --name $VM_NAME   --zone $ZONE   --network-interface subnet-name=default-$ZONE,nat-ip-version=ipv4  --memory 2GB  --cores 2  --core-fraction 20  --hostname centos-$VM_NAME  --preemptible   --create-boot-disk image-folder-id=standard-images,size=10,type=network-hdd,image-family=centos-7   --ssh-key ~/.ssh/id_ed25519.pub >/dev/null
        yc compute instance create   --name $VM_NAME   --zone $ZONE   --network-interface subnet-name=default-$ZONE,nat-ip-version=ipv4  --memory 4GB  --cores 2  --core-fraction 20  --hostname debian-$VM_NAME  --preemptible   --create-boot-disk image-folder-id=standard-images,size=20,type=network-hdd,image-family=debian-11   --ssh-key ~/.ssh/id_ed25519.pub >/dev/null
        if [ $? -ne 0 ]; then echo "ОШИБКА. ВМ $VM_NAME не создана"; fi 
    else
        echo "ВМ $VM_NAME уже существует"
    fi

    VM_IP=$(yc compute instance get $VM_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs)
    echo "$VM_NAME ansible_host=$VM_IP ansible_connection=ssh ansible_ssh_user=yc-user" >> ~/Thesis-on-the-Profession/ansible/hosts
done

sleep 30s

#scp ~/packages/elasticsearch-7.17.11-amd64.deb yc-user@$(yc compute instance get $LOGS_VM1_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs):/tmp/
#scp ~/packages/kibana-7.17.11-amd64.deb yc-user@$(yc compute instance get $LOGS_VM2_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs):/tmp/

echo "server.port: 5601
server.host: \"0.0.0.0\"" > ~/Thesis-on-the-Profession/logs/kibana.yml
echo "elasticsearch.hosts: [\"http://$(yc compute instance get $LOGS_VM1_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs):9200\"]" >> ~/Thesis-on-the-Profession/logs/kibana.yml
echo "server.publicBaseUrl: \"http://$(yc compute instance get $LOGS_VM2_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs):5601/\"
elasticsearch.username: \"kibana_system\"
elasticsearch.password: \"elastic\"" >> ~/Thesis-on-the-Profession/logs/kibana.yml



sleep 1s

cd ~/Thesis-on-the-Profession/ansible
ansible-playbook logs.yml

#sleep 1s



