#!/bin/bash
wget https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz
tar xvfz node_exporter-1.6.0.linux-amd64.tar.gz
cd cd node_exporter-1.6.0.linux-amd64/
#./node_exporter  #Проверяем доступность : http://127.0.0.1:9100/metrics
mkdir /etc/prometheus/node-exporter
cp ./* /etc/prometheus/node-exporter
chown -R prometheus:prometheus /etc/prometheus/node-exporter/
#nano /etc/systemd/system/node-exporter.service #Содержимое файла ниже в блоке кода
systemctl enable node-exporter
systemctl start node-exporter
#systemctl status node-exporter

