global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090', 'localhost:9100']

  - job_name: "web1"
    scrape_interval: 5s
    static_configs:
      - targets: ['84.201.157.177:9100', '84.201.157.177:4040']

  - job_name: "web2"
    scrape_interval: 5s
    static_configs:
      - targets: ['158.160.77.185:9100', '158.160.77.185:4040']

