#!/bin/bash
sudo useradd --no-create-home --shell /bin/false prometheus
#wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-386.tar.gz
wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
#tar xvfz prometheus-2.45.0.linux-386.tar.gz
tar xvfz prometheus-2.45.0.linux-amd64.tar.gz
#cd prometheus-2.45.0.linux-386/
cd prometheus-2.45.0.linux-amd64/
sudo mkdir /etc/prometheus
sudo mkdir /var/lib/prometheus
sudo mkdir /var/log/prometheus
sudo cp  ./prometheus promtool /usr/local/bin/
sudo cp -R ./console_libraries /etc/prometheus
sudo cp -R ./consoles /etc/prometheus
sudo cp -f ./prometheus.yml /etc/prometheus
sudo chown -R prometheus:prometheus /etc/prometheus
sudo chown -R prometheus:prometheus /var/lib/prometheus
sudo chown -R prometheus:prometheus /var/log/prometheus
sudo chown prometheus:prometheus /usr/local/bin/prometheus
sudo chown prometheus:prometheus /usr/local/bin/promtool
/usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries
#sudo nano /etc/systemd/system/prometheus.service
sudo cp -f /tmp/prometheus.service /etc/systemd/system/prometheus.service
sudo cp -f /tmp/prometheus.yml /etc/prometheus/prometheus.yml
sudo systemctl enable prometheus.service
sudo systemctl start prometheus.service
#systemctl status prometheus.service

