---
- name: Elastiksearch+Kibana
  hosts: logs
  become: true
  
  tasks:
  - name: Update
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Elastiksearch
  hosts: vm-elastik
  become: true
  
  tasks:
  - name: Push elasticsearch-7.17.11-amd64.deb
    ansible.builtin.copy:
      src: ~/packages/elasticsearch-7.17.11-amd64.deb
      dest: /tmp/elasticsearch-7.17.11-amd64.deb
      remote_src: false
      mode: preserve
  
  - name: Install elasticsearch
    ansible.builtin.apt:
      deb: /tmp/elasticsearch-7.17.11-amd64.deb

  - name: Copy elasticsearch.yml
    ansible.builtin.copy:
      src: ~/Thesis-on-the-Profession/logs/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      mode: preserve

  - name: Enable service elasticsearch
    ansible.builtin.service:
      name: elasticsearch.service
      enabled: yes
  
  - name: Start service elasticsearch
    ansible.builtin.service:
      name: elasticsearch.service
      state: started

  - name: Generic question with multiple different responses
    ansible.builtin.expect:
      chdir: /usr/share/elasticsearch/bin/
      echo: true
      command: /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
      responses:
        (.*)Please confirm that you would like to continue (.*): "y"
        'Enter password for [elastic]: ': "elastic"
        (.*)Reenter password for [elastic](.*): "elastic"
        Enter password for [apm_system](.*): "elastic"
        Reenter password for [apm_system](.*): "elastic"
        Enter password for [kibana_system](.*): "elastic"
        Reenter password for [kibana_system](.*): "elastic"
        Enter password for [logstash_system](.*): "elastic"
        Reenter password for [logstash_system](.*): "elastic"
        Enter password for [beats_system](.*): "elastic"
        Reenter password for [beats_system](.*): "elastic"
        Enter password for [remote_monitoring_user](.*): "elastic"
        Reenter password for [remote_monitoring_user](.*): "elastic"
        
    
- name: Kibana
  hosts: vm-kibana
  become: true
  
  tasks:
  - name: Push kibana-7.17.11-amd64.deb
    ansible.builtin.copy:
      src: ~/packages/kibana-7.17.11-amd64.deb
      dest: /tmp/kibana-7.17.11-amd64.deb
      remote_src: false
      mode: preserve

  - name: Install kibana
    ansible.builtin.apt:
      deb: /tmp/kibana-7.17.11-amd64.deb

  - name: Copy kibana.yml
    ansible.builtin.copy:
      src: ~/Thesis-on-the-Profession/logs/kibana.yml
      dest: /etc/kibana/kibana.yml
      mode: preserve

  - name: Enable service kibana
    ansible.builtin.service:
      name: kibana.service
      enabled: yes
  
  - name: Start service kibana
    ansible.builtin.service:
      name: kibana.service
      state: started
...
