---
- name: Prometheus and Node-exporter
  hosts: vm-prometheus
  become: true
  
  tasks:
  - name: create user prometheus
    ansible.builtin.user:
    name: prometheus
    comment: prometheus
    group: prometheus
    shell: /bin/false
    create_home: false 

  - name: download prometheus
    ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
    dest: /tmp/
    

  - name: copy files
    copy: src={{ item.0 }} dest={{ item.1 }}
    with_together:
      - [ '~/Thesis-on-the-Profession/monitoring/prometheus.service', '~/Thesis-on-the-Profession/monitoring/prometheus.yml' ]
      - [ '/etc/systemd/system/', '/etc/prometheus/' ]



  - name: "Restart service nginx"
    service:
      name: nginx
      state: restarted
    retries: 2
    delay: 2
    become: true
  handlers:
  - name: Start nginx 
    service: name=nginx state=started
...
