---
- name: Prometheus and Node-exporter
  hosts: vm-prometheus
  become: true
  
  tasks:
  - name: copy config files
    copy: src={{ item.0 }} dest={{ item.1 }}
    with_together:
      - [ '~/Thesis-on-the-Profession/monitoring/prometheus.service', '~/Thesis-on-the-Profession/monitoring/prometheus.yml', '~/Thesis-on-the-Profession/monitoring/node-exporter.service' ]
      - [ '/etc/systemd/system/', '/etc/prometheus/', '/etc/systemd/system/' ]
      
  - name: copy script install prometheus
    copy:
      src: ~/Thesis-on-the-Profession/monitoring/prometheus-install
      dest: /tmp/
      owner: yc-user
      group: yc-user
      mode: u+x,g+x,o+x
    
  - name: copy script install node-exporter
    copy:
      src: ~/Thesis-on-the-Profession/monitoring/node-exporter-install
      dest: /tmp/
      owner: yc-user
      group: yc-user
      mode: u+x,g+x,o+x
      
  - name: start script install prometheus
    ansible.builtin.command: ./prometheus-install
    args:
      chdir: /tmp/
  
  - name: start script install node-exporter
    ansible.builtin.command: ./node-exporter-install
    args:
      chdir: /tmp/
  
  - name: checking service status
    ansible.builtin.command: systemctl status "{{ item }}"
    with_items:
    - prometheus
    - node-exporter
    register: result
    ignore_errors: yes
    
  - name: showing report
    debug:
     var: result

...
