#!/bin/bash
#

LOGS_VM1_NAME=vm-elastic
#LOGS_VM2_NAME=vm-kibana

WEB_VM1_NAME=vm-web1
WEB_VM2_NAME=vm-web2

MONS_VM1_NAME=vm-prometheus
#MONS_VM2_NAME=vm-grafana

#
#Отвязываем неиспользуемые публичные IP адреса от ВМ
#
echo -e "\n# Отвязываем неиспользуемые публичные IP адреса от ВМ #\n"
for VM_NAME in $LOGS_VM1_NAME $WEB_VM1_NAME $WEB_VM2_NAME $MONS_VM1_NAME
do
    yc compute instance get $VM_NAME &>/dev/null
    if [ $? -eq 0 ]; then
        echo "## ВМ $VM_NAME найдена.."
        yc compute instance remove-one-to-one-nat --name=$VM_NAME --network-interface-index=0 --async  &>/dev/null
        if [ $? -ne 0 ]; then echo "## ОШИБКА. Публичный IP адрес от ВМ $VM_NAME не отвязан"; exit 1; fi 
    fi
done
# Ожидаем освобождения публичных IP адресов
echo "## Ожидаем освобождения публичных IP адресов..."
for VM_NAME in $LOGS_VM1_NAME $WEB_VM1_NAME $WEB_VM2_NAME $MONS_VM1_NAME
do
    while [ -n "$(yc compute instance get $VM_NAME |grep -iE "^[ ]{8}address: " |sed 's/address://' |xargs)" ]
    do
        sleep 3
    done
    echo "## ВМ $VM_NAME - публичных IP адрес освобожден"
done


